server:
  port: 8085

spring:
  application:
    name: login

  h2:
    console:
      enabled: true
      path: /h2-console


  datasource:
    url: jdbc:log4jdbc:h2:tcp://localhost/~/test  # 최초 한 번:   jdbc:h2:~/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.login.model

logging:
  level:
    jdbc.sqlonly: DEBUG      # 물음표(?) 대신 실제 값이 치환된 SQL 출력
    jdbc.sqltiming: INFO     # SQL + 실행 시간
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF
