server:
  port: 8085

spring:
  application:
    name: login

  datasource:
    url: jdbc:h2:tcp://localhost/~/test  # 최초 한 번: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

